[package]
name = "parsql-sqlite"
description = "Parsql için sqlite entegrasyonunu sağlayan küfedir."
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rusqlite = { version = "0.32.1" }
parsql-core = { path = "../parsql-core" }
parsql-macros = { path = "../parsql-macros" }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
nanoid = "0.4.0"

[[bench]]
name = "sqlite_benches"
harness = false

[lints]
workspace = true
