[package]
name = "parsql-sqlite"
description = "Parsql için sqlite entegrasyonunu sağlayan küfedir."
version.workspace = true
license.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
rusqlite = { version = "0.32.1" }
parsql = { path = "../", version = "0.1.0", features = ["sqlite"], default-features = false }
parsql-macros = { path = "../parsql-macros", version = "0.1.0" }
