[package]
name = "parsql-sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
rusqlite = { version = "0.32.1" }
parsql = { path = "../", version = "0.1.0", features = ["sqlite"], default-features = false }
parsql-macros = { path = "../parsql-macros", version = "0.1.0", features = ["sqlite"], default-features = false }
