[package]
name = "parsql-core"
description = "Parsql için temel trait'leri barındıran küfedir."
authors.workspace = true
edition.workspace = true
keywords.workspace = true
repository.workspace = true
version.workspace = true
license.workspace = true

[dependencies]

[lints]
workspace = true
